name: Scrape Latest Courses

on:
  schedule:
    - cron: 0 0 1 * *
    - cron: 0 0 10 * *
    - cron: 0 0 16 * *
    - cron: 0 0 20 * *
    - cron: 0 0 25 * *
    - cron: 0 0 30 * *

  workflow_dispatch: {}
  workflow_call: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@main
      - name: Add Python
        uses: actions/setup-python@main
        with:
          python-version: "3.10"
      - name: Scrape Courses
        run: |
          pip install requests beautifulsoup4
          python ./scrapers/fetch-courses.py
      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@main
        id: verify-changed-files
        with:
          files: data/base-courses.json
      - name: Fetch Schedule/GPA if Courses Changed.
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          python ./scrapers/fetch-schedule.py
          python ./scrapers/fetch-gpa.py
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: "DD-MM-YYYY"
      - name: Pull Remote Changes
        run: git pull
      - name: Commit Back Changed Data
        uses: stefanzweifel/git-auto-commit-action@main
        with:
          commit_message: "Latest Courses data: ${{ steps.time.outputs.time }}"
          commit_author: Author <actions@github.com>
          file_pattern: data/*.json
