name: Scrape Latest Schedule

on:
  schedule:
    - cron: 0 0 1 * *
    - cron: 0 0 10 * *
    - cron: 0 0 16 * *
    - cron: 0 0 20 * *
    - cron: 0 0 25 * *
    - cron: 0 0 30 * *

  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@main
      - name: Add Python
        uses: actions/setup-python@main
        with:
          python-version: "3.10"
      - name: Scrape Courses
        run: |
          pip install requests beautifulsoup4
          python ./scrapers/fetch-schedule.py
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: "DD-MM-YYYY"
      - name: Commit Back Changed Data
        uses: stefanzweifel/git-auto-commit-action@main
        with:
          commit_message: "Latest Schedule data: ${{ steps.time.outputs.time }}"
          commit_author: Author <actions@github.com>
          file_pattern: data/*.json
